##---
# Source: strimzi-kafka-operator/templates/04-Crd-kafkatopic.yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.kafka.strimzi.io
  labels:
    app: 'strimzi'
    chart: 'strimzi-kafka-operator-0.1.0'
    component: kafkatopics.kafka.strimzi.io-crd
    release: 'RELEASE-NAME'
    heritage: 'Tiller'
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaTopic
    listKind: KafkaTopicList
    singular: kafkatopic
    plural: kafkatopics
    shortNames:
    - kt
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            partitions:
              type: integer
              minimum: 1
            replicas:
              type: integer
              minimum: 1
              maximum: 32767
            config:
              type: object
            topicName:
              type: string
      required:
      - spec
