##---
# Source: strimzi-kafka-operator/templates/04-Crd-kafkauser.yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkausers.kafka.strimzi.io
  labels:
    app: 'strimzi'
    chart: 'strimzi-kafka-operator-0.1.0'
    component: kafkausers.kafka.strimzi.io-crd
    release: 'RELEASE-NAME'
    heritage: 'Tiller'
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaUser
    listKind: KafkaUserList
    singular: kafkauser
    plural: kafkausers
    shortNames:
    - ku
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            authentication:
              type: object
              properties:
                type:
                  type: string
          required:
          - authentication
      required:
      - spec
