include::common/attributes.adoc[]

= Using {ProductLongName}

{ProductLongName} provides a way to run an Apache Kafka cluster on {ProductPlatformLongName} in various deployment configurations.
This guide describes how to install and use {ProductLongName}.

== Overview

Apache Kafka is a popular platform for streaming data delivery and processing. For more details about Apache Kafka
itself visit http://kafka.apache.org[Apache Kafka website]. The aim of {ProductName} is to make it easy to run
Apache Kafka on {ProductPlatformName}.
{ProductName} is based on Apache Kafka 1.1.0.

{ProductName} consists of two main components:

Cluster Operator:: Responsible for deploying and managing Apache Kafka clusters within {ProductPlatformName} cluster.
Topic Operator:: Responsible for managing Kafka topics within a Kafka cluster running within {ProductPlatformName} cluster.

include::getting-started.adoc[]

include::cluster-operator.adoc[]

include::topic-operator.adoc[]

include::security.adoc[]

include::faq.adoc[]

ifdef::InstallationAppendix[]
include::appendix_deploying_kubernetes_openshift_cluster.adoc[]
endif::InstallationAppendix[]

[appendix]
[[kafka_resource_reference]]
## The `Kafka` resource reference
include::appendix_kafka_crd.adoc[]

[appendix]
[[KafkaConnect_resource_reference]]
## The `KafkaConnect` resource reference
include::appendix_kafka_connect_crd.adoc[]

[appendix]
[[KafkaConnectS2I_resource_reference]]
## The `KafkaConnectS2I` resource reference
include::appendix_kafka_connect_s2i_crd.adoc[]


ifdef::MetricsAppendix[]
include::appendix_metrics.adoc[]
endif::MetricsAppendix[]
